# Generated by Django 2.2 on 2020-05-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_is_classics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='images',
            new_name='image',
        ),
    ]
