# Generated by Django 2.2 on 2020-05-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursetag_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='weight',
            field=models.CharField(choices=[('1', '低'), ('2', '中'), ('3', '高')], default='1', max_length=1, verbose_name='权重'),
        ),
    ]
